#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rpmfile
Version  : 1.0.8
Release  : 4
URL      : https://files.pythonhosted.org/packages/23/79/27e50c988bfbfabb75d17bff6cf1ae351104c3446e5a592823ff2a155505/rpmfile-1.0.8.tar.gz
Source0  : https://files.pythonhosted.org/packages/23/79/27e50c988bfbfabb75d17bff6cf1ae351104c3446e5a592823ff2a155505/rpmfile-1.0.8.tar.gz
Summary  : Read rpm archive files
Group    : Development/Tools
License  : MIT
Requires: rpmfile-bin = %{version}-%{release}
Requires: rpmfile-python = %{version}-%{release}
Requires: rpmfile-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pip
BuildRequires : setuptools_scm-python

%description
# rpmfile
[![Build Status](https://travis-ci.org/srossross/rpmfile.svg?branch=master)](https://travis-ci.org/srossross/rpmfile)
[![Actions Status](https://github.com/srossross/rpmfile/workflows/Tests/badge.svg?branch=master&event=push)](https://github.com/srossross/rpmfile/actions)
[![PyPI version](https://img.shields.io/pypi/v/rpmfile.svg)](https://pypi.org/project/rpmfile)

%package bin
Summary: bin components for the rpmfile package.
Group: Binaries

%description bin
bin components for the rpmfile package.


%package python
Summary: python components for the rpmfile package.
Group: Default
Requires: rpmfile-python3 = %{version}-%{release}

%description python
python components for the rpmfile package.


%package python3
Summary: python3 components for the rpmfile package.
Group: Default
Requires: python3-core
Provides: pypi(rpmfile)

%description python3
python3 components for the rpmfile package.


%prep
%setup -q -n rpmfile-1.0.8
cd %{_builddir}/rpmfile-1.0.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1625851680
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rpmfile

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
